/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.demo

class GroovyApp {
    String getGreeting() {
        return 'Hello Gradle'
    }

    static void main(String[] args) {
        println new GroovyApp().greeting
    }
}
