/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.demo

import spock.lang.Specification

class GroovyAppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new GroovyApp()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
